site_name: PocketSOC Documentation
site_description: Documentation for pocketsoc setup

theme:
  name: material
  language: en
  features:
    - content.code.copy


nav:
  - Home: index.md
  - Admin:
    - Deployment: Admin/deployment.md
    - Design: Admin/design.md
  - Trainees:
    - Access: Trainees/access.md
    - Exercise 1: Trainees/portainer.md
    - Exercise 2: Trainees/opensearch.md
    - Exercise 3: Trainees/explore.md
    - Exercise 4: Trainees/misp.md
    - Exercise 5: Trainees/generate.md
    - Exercise 6: Trainees/analyse.md


#repo_url: https://github.com/my-repo/project
#repo_name: "GitHub"

plugins:
  - search

copyright: |
  &copy; 2024 <a href="https://github.com/azahmd"  target="_blank" rel="noopener">PocketSOC</a>
